#!/bin/sh
#
# RK3399 media legacy post-inst script
#

DEFAULTUSER=$(getent passwd 1000 | cut -f1 -d:)

# Disable window compositing
[ -f /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml ] && sed -i -e 's/name="use_compositing" type="bool" value="true"/name="use_compositing" type="bool" value="false"/g' /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
sed -i -e 's/name="use_compositing" type="bool" value="true"/name="use_compositing" type="bool" value="false"/g' /home/$DEFAULTUSER/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml

# Workaround for older armbian configs
rm -f /etc/X11/xorg.conf.d/02-driver.conf

# Config user and env for Kodi service
systemd-sysusers
systemd-tmpfiles --create

# Suggest reboot
echo -e "\n\033[0;32m#########################################\n# Configuration finished. PLEASE REBOOT #\n#########################################\033[0m\n"

exit 0
