#!/bin/sh
#
# tinkerboard media legacy post-inst script
#

DEFAULTUSER=$(getent passwd 1000 | cut -f1 -d:)

# Disable window compositing
[ -f /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml ] && sed -i -e 's/name="use_compositing" type="bool" value="true"/name="use_compositing" type="bool" value="false"/g' /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
sed -i -e 's/name="use_compositing" type="bool" value="true"/name="use_compositing" type="bool" value="false"/g' /home/$DEFAULTUSER/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml

systemctl restart lightdm.service

exit 0
